[workspace]
members = [
    # 1detla
    "scripts/batch_swap_exact_in_script",
    "scripts/batch_swap_exact_out_script",
    "scripts/composer_script",
    "dex_lib/executor",
    # margin
    "contracts/margin_account",
    "contracts/account_proxy",
    "contracts/account_factory",
    "contracts/beacon",
    "contracts/beacon_utils",
    # libs
    "dex_lib/mira_v1/interfaces",
    "dex_lib/mira_v1/math",
    "dex_lib/mira_v1/utils",
    "dex_lib/logger_abi",
    "scripts/add_liquidity_script",
    "scripts/create_pool_and_add_liquidity_script",
    "contracts/mocks/mock_token",
    "contracts/mocks/mock_swaylend",
    "contracts/logger",
    "order_utils",
    "one_delta_orders",
    "order_router",
]
