[project]
authors = ["1delta"]
entry = "main.sw"
license = "Apache-2.0"
name = "mock_swaylend"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.25.2" }
market_abi = { path = "../../../dex_lib/swaylend" }
