[project]
authors = ["Achthar"]
entry = "main.sw"
license = "Apache-2.0"
name = "order_router"

[dependencies]
order_utils = { path = "../order_utils" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
