[project]
authors = ["1delta"]
entry = "main.sw"
license = "Apache-2.0"
name = "account_logic"

[dependencies]
executor = { path = "../../dex_lib/executor" }
interfaces = { path = "../../dex_lib/mira_v1/interfaces" }
market_abi = { path = "../../dex_lib/swaylend" }
account_utils = { path = "../account_utils" }
