[project]
authors = ["1delta"]
entry = "main.sw"
license = "Apache-2.0"
name = "batch_swap_exact_out_script"

[dependencies]
executor = { path = "../../dex_lib/executor" }
interfaces = { path = "../../dex_lib/mira_v1/interfaces" }
mira_v1_swap = { path = "../../dex_lib/mira_v1/swap" }
math = { path = "../../dex_lib/mira_v1/math" }
utils = { path = "../../dex_lib/mira_v1/utils" }
