[project]
authors = ["Mira AMM"]
entry = "main.sw"
license = "Apache-2.0"
name = "create_pool_and_add_liquidity_script"

[dependencies]
interfaces = { path = "../../dex_lib/mira_v1/interfaces" }
utils = { path = "../../dex_lib/mira_v1/utils" }
