[project]
authors = ["Achthar"]
entry = "main.sw"
license = "Apache-2.0"
name = "account_proxy"

[dependencies]
beacon_utils = { path = "../beacon_utils" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.25.2" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.7.0" }